### ISSUE TITLE
Derek's testing & feedback - June 20th 2018 

### ISSUE THREAD

**Issue by derekmorin** [talentivan/tarbarnapp#14]
# Phase 1 Feedback

### For Ivan
You did a great job!

### For Bogdan
- [ ] Navigation is missing (top bar, eg. Back button when i'm inside the screen to create an exit popup). That's probably @bogdanrn who will handle that...

- [ ] We should add a "Pause/Resume" button in the main screen at the left of the "pen (edit)" button. Therefore, we would need a "paused" tag, like <span class="tag blue">blue</span>
 While testing, I wanted to pause one Animated Tab, because I want to stop it and still be able to use it later without having to recreated it. I know we will add a "Quick Setup" icon/button too, but this Quick Setup accomplishes a different purpose, that is for changing dates quickly when I know exactly when I want to schedule the tab title. The "Pause" icon/button is for when I don't know when I want to schedule it OR I just don't want to loose it and have to start over again later. Re-creating an exit popup is even more time-consuming than an Animated Tab Title, so that legitimates even more the existence of a Pause/Resume button. this means a new key needs to be added to the schema:
published: { bool, defaultValue:false}

- [ ] when i clicked on DELETE icon in the main screen, for Exit popups and Animated tab titles, 
i expected a swal confirmation modal window like "Are you sure?". @bogdanrn told me just now that he will add it himself:
```
bogdan [11:06 AM]
i haven't told him to add it
because i'll add it using the ShopifyApiblblabla
which only works in the embedded app
i would of had to delete his code if he did it
```

<hr>

### For Ivan

- [x] the popup we have so far is incomplete. The w.onbeforeunload = function(){ } is missing. So we have 2 options: 
_Option 1)_ We implement it and this makes the popup show if user is about to close the tab (or near the "x" to close it) 
_Option 2)_ we add a field admin side to let merchants select the Popup Trigger:
**Display the popup when customers:**
- Leave or switch tab
- Intent to close the tab

The "intent to close the tab" should be what an exit intent popup is by definition, like this one: http://beeker.io/exit-intent-popup-script-tutorial or that one http://qnimate.com/exit-intent-using-javascript/ (choose whatever librairy you prefer).

- [x] The button color picker field should be moved under that Button (Call to action) field., and above the Coupon Code field and should be renamed to "Button Color"
![image](https://user-images.githubusercontent.com/6986546/41674487-2350c43a-748e-11e8-8435-127ba752fba1.png)

- [x] In the text "Create one in Discounts and paste it above", the word "Discounts" should be linked to /admin/discounts in a new tab (target blank)
![image](https://user-images.githubusercontent.com/6986546/41674437-fc3c1e76-748d-11e8-964f-bde0282a064f.png)

- [x] I don't understand, in the right column the fields "Title of Discount Popup" and "Message of Discount Popup". Are they related to the popup displayed once the discount was applied? If so, then simply make it clearer by adding a small text below the field "Title of Discount Popup" that says:
_Second popup displayed if customers get the discount_

- [x] I think the popup is now displayed only once per session, right? We should write it down somewhere, because merchants will test it once and then email us to complain that is doesn't work anymore... so unless we had the option to change the frequency of display like "Always display", "Display once per session", "Display once ever X days" or idk which settings we will have there, but unless we had it in phase 1, we really need to write down that the popup shows only once... For now, simply add this text in the Exit popup screen:
_The Exit Popup is displayed once per visit_

- [x] The second popup (the "Congrats" one) should contain the checkmark icon at top, so in swal2 you need to put  type: 'success' like you did for the first popup.
![image](https://user-images.githubusercontent.com/6986546/41674461-079b7b04-748e-11e8-808d-f824f1965716.png)

### For Bogdan
- [ ] In the second popup, I can't change the button text " OK ". Should I be able to edit it @bogdanrn ? I don't know... you tell me... maybe in phase 2 we could have a choice to "Go to Cart" or "Go to Checkout" on click

- [ ] I couldn't test if the discount was really applied at checkout... @bogdanrn did you manage to test this? For me, the URL structure once I clicked the Get Discount button in the popup was incorrect, so that's why I ask if it works for real.

<hr>

### For Ivan
- [x] below the "Tab Text" field, I would add in italic "Emojis supported"
![image](https://user-images.githubusercontent.com/6986546/41674152-3309dbd8-748d-11e8-9ea5-9d3698b702df.png)

- [x] A space (line jump or new row) is missing above the "Show Options" label of the Animated Tab Title section
![image](https://user-images.githubusercontent.com/6986546/41674147-2aa523e4-748d-11e8-9538-40a21fea7256.png)

- [x] We definitely need the dates in the tag displayed in the main screen. 
For the Scheduled ones, you can use `<span class="tag yellow pending">Scheduled on [date]</span>`
For the Active ones, you can use `<span class="tag green pending">Active until [date]</span>`
For the Ended ones, you can use `<span class="tag grey">Ended on [date]</span>`
The [date] format could be dd/mm/yyyy or mm/dd/yyyy or whatever what you prefer, I don't mind.

- [ ] If I set tab title A displayed "Only if tab is active" and I set tab title B "Only if tab is inactive", both should be "Active" and coexisting without any conflict. Right now, tab A stays "Active" and Tab B becomes "In Queue".
In other words, merchants should be able to create two non conflicting tabs and they can be published at the same time. I Imagine merchants will use it like this:
tab active = 20% discount store wide
tab inactive = 25% we joked, please come back

- [ ] About the priority of display: If there is a conflict with 2 active tabs, one "Always display" and one "only if tab is active/inactive", then the priority should go to "Only if tab is active" and "Only if tab is inactive" over "Always display"

### For Bogdan

- [ ] Related to datepicker, I don't think we should allow to select dates in the past... but it's a small glitch, I can live with it.

- [ ] *Could be Phase 2* I think we should allow timer picker as well inside the date picker... isn't it a timepicker in the librairy we are using? Because now I can only set a 1-day period (24h), and some merchants will want it to be more flexible (eg. a 5h period).

- [x] What happens if I don't select any date? It runs right now, right? I mean if I don't schedule it, it runs, right? Oh I see that we have a "Not scheduled" tag. I thought it was running automatically now if you don't set any scheduled dates. But it's fine, let it like this.

- [ ] For the mobile tab color, we should make the label clickable with a link to a youtube video OR we put below the color picker a link (eg. See example) that opens a youtube video. 

- [ ] Small UI glitch my side, the month word is cut in the datepicker... if you can't reproduce it, I can live with it. 
![image](https://user-images.githubusercontent.com/6986546/41674250-746307c6-748d-11e8-8623-c0ab23ec2e97.png)
